services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:Chigozie0@postgres:5432/todo_app
      PORT: 3000

  postgres:
    image: postgres:17-alpine
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chigozie0
      POSTGRES_DB: todo_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: